### PR TITLE
Project Input

### LINKED ISSUE #2857: Edit view redesign - Project input
### 💻 Environment
Platform: macOS

### 📒 Description
Projects input has 4 different components:
- Text input
- Autocomplete (NSPopover)
- Add Project Form
- Project color select Form
- Add Client Form

**Text Input**
It's an input field with a down arrow button on the right side. Clicking on the down arrow should open the autocomplete list (similar to current implementation)

**Autocomplete**
Typing text in the input will filter the autocomplete list. The `+ Create a new Project` row is always visible in the bottom of the autocomplete. It is not part of the items list and does not scroll.

#### Add Project Flow
When the user presses the `+ Create a new Project` with mouse or activates it with the keyboard the contents of the NSPopover are replaced with the `Add Project Form` content. The text that was typed into the input field is copied to the project name field in the `New Project` form.

**New Project Form**
New Project has the following components:

- Cancel Button - Clears the "New Project Form" and goes back to initial autocomplete listing
- Add Button - triggers adding the new project (validation and saving the project). Then selects the newly created project for the time entry, clears the "New Project Form" and closes popup.
- Project name Input - value is initially copied from the autocomplete input field. User can edit is as they please.
- Project color dot - described in detail in: #2856
- Workspace Select - It's a regular select box without autocomplete. (Similar to current solution)
- Client autocomplete - Autocomplete of client names. If the inserted text has no matches text `No matching items`

**New Client Flow**
If user types in client name that does not have exact match a new line with text `+Create Client "Client Name"` will appear. If the client name is too long it shows `...` at the end of the name.
Clicking this new row will create client and nothing else.

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
It's a huge ticket, which is trying to introduce the complete new logic for Project Input.

### 🕶️ Types of changes
- **New feature** (non-breaking change which adds functionality)
- **Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes
- [x] Reusable AutoCompleteView, AutoCompleteDataSource, AutoCompleteTextField
- [x] Menu Windows: Able to expand cross the main Windows
- [x] AutoComplete logic for Project, Client and Workspace
- [x] Basic layout and logic for Color Picker
- [x] Fill TimeEntry data from selected TimeEntry from the list
- [x] Logic for create new Client and Project from Library (The UI and basic logic are done. It's time to call func from library to make it works)
- [x] Finalize the final design: We have few minor issues. Such as "Borderless Windows", "Shadow on windows", ...
- [x] Save Time Entry Name after editing
### 👫 Relationships
Close #2857 

### 🔎 Review hints
- Main logic of Project Input should work

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
It's ready for reviewing now @IndrekV 👍

**Comment by NghiaTranUIT** [comment]
Please note that the color pick design hasn't completely done yet. I will finalize the design in https://github.com/toggl/toggldesktop/issues/2856

In this Pull Request, the main logic of Color Picker is done. Thus, we're able to select pre-define colors and custom color.

**Comment by NghiaTranUIT** [comment]
Yo, the Git history is clean now 👍

**Comment by IndrekV** [comment]
- [ ]  Tabbing not working in "create project" form
- [ ]  Unable to select "+ create project" or "+ create client" items with keyboard
- [ ]  Pressing "Add" button in "create project" form does not do anything if no client is selected.
- [ ]  The solution for the wrong alignment with project dot would be to trigger rendering twice or something like that. The same way how it renders properly after loading the edit popup with new data the first time.
- [ ]  Pressing tab when "delete" button is focused should move to description field. Currently it moves to project autocomplete.

**Comment by NghiaTranUIT** [comment]
Thank for valuable feedback. I will address all of them in this today 👍

**Comment by NghiaTranUIT** [comment]
Rebased successfully 👍

**Comment by IndrekV** [comment]
Nice work. All the things that are checked are now fixed. Keep it up @NghiaTranUIT !

**Comment by NghiaTranUIT** [comment]
>  The solution for the wrong alignment with project dot would be to trigger rendering twice or something like that. The same way how it renders properly after loading the edit popup with new data the first time.

Thank for the hint, I tries to resign the become first responder in order to re-render at https://github.com/toggl/toggldesktop/pull/2907/commits/66bc873893b6d089fa843b3ec18ce4f18a1f691c. It works 💯

**Comment by IndrekV** [comment]
A new round of feedback:

- [ ]  If you delete the project name and then move away from the project field the project should be removed and the project color should be reset to gray
- [ ] Dropdown should not be automatically opened when the project field gets the focus
- [ ] If you select the project the dropdown should be closed. Currently, it closes it the change triggers the filter and shows the drop down again
- [ ] `No project` item is missing from autocomplete dropdown
- [ ] Clicking the down arrow to open the dropdown should show all the items.  Currently it only shows items that match the selected project. Here's a gif to illustrate.
mac-ac

**Comment by NghiaTranUIT** [comment]
Luckily, I found the elegant way to support Keyboard for the note `Unable to select "+ create project" or "+ create client" items with keyboard` with this fix https://github.com/toggl/toggldesktop/pull/2907/commits/e169bb3c3a6b509079862b9a3dc34a155703956e

**Comment by NghiaTranUIT** [comment]
Regarding 
```
No project item is missing from autocomplete dropdown
```
We can delete the selected project by deleting all text in Project TextField, then moving away.

Overall, it's all done and ready for next review round now @IndrekV  👍

**Comment by IndrekV** [comment]
I think the workspace name items are missing. I know that it was not described in the design, but we have to have it. Right now it's confusing to see `NO CLIENT` multiple times and no clear indication of where one workspace ends and another one starts.

I think the design could be similar to old autocomplete solution. The workspace name is aligned to center in uppercase and has a gray border under it.

**Comment by IndrekV** [comment]
When I create a project with color from the color picker it is not properly saved. I cannot select it as a project to another time entry.

Here is an example (I created project `proj 34`)

mac_project_select_2

**Comment by NghiaTranUIT** [comment]
From you GIF, the "We" Time Entry, which is associated with "Project 34" in Thu, 11 Apr, was unable to sync(). You can notice the Red Error icon in right-bottom.

I believe that in this case, the Project#34's projectID is nil, so it couldn't assign to any project -> Which cause the empty project.

Do you think that the Desktop Library should only return `valid` project? From what I experience, the Desktop Library return all projects. Thus, sometime, it's invalid or haven't synced yet 🤔

**Comment by NghiaTranUIT** [comment]
@IndrekV Please help me to do a quick review on this fix (https://github.com/toggl/toggldesktop/pull/2907/commits/a07291137ac1f6efd34344e169b8b8c6c40fee28). (make sure you check out new commit from Origin, since I rebase from Master for the "Focus Jump" fix)

Technically, after creating new Project ID, I store the ProjectGUI. So, if the user re-assign the Project (hasn't had ID yet), it will assign the GUID.

As a result, the bug is totally gone.

**Comment by IndrekV** [comment]
The project select bug seems to be gone.

**Comment by IndrekV** [comment]
I'm going to double check the autocomplete filtering. Before we had autocomplete that would work with multiple words and not only exact match. It seems that currently when space is in the filter it also expects space in the items.

**Comment by IndrekV** [comment]
The filtering is now working ok, but I found another bug. 

When adding project the client dropdown should show the clients of the selected workspace. If workspace selection changes it should reload the data in client select. Currently, it always shows all the clients from all workspaces.

**Comment by IndrekV** [comment]
Thank you for sticking with me on this longest PR review @NghiaTranUIT . This is now OK and we can merge!

**Pull request merged**
