### PR TITLE
UI Tweak for New design

### LINKED ISSUE #2890: Timeline UI - changing days
### 💻 Environment
Platform: macOS

### 📒 Description
Add LEFT and RIGHT keyboard keys to switch the visible day data in the timeline view

### LINKED ISSUE #2980: UI Tweaks for new mac design
### 💻 Environment
Platform: macOS

### 📒 Description

- [x] ESC should close edit popup when there is no opened autocomplete popup
- [x] Clicking on the dark overlay in main window autocomplete should close the dropdown
- [x] After signup when users starts entry the first empty state changes to spider. It should stay the same as long as at least 1 entry has been in the list. As we show 9 entries in the list and actually load more we could detect if spider should be shown that way somehow
- [x] Unable to open up “create client” with clicking the arrow in client field (When it’s a fresh account and there are no clients) [Might be same with project autocomplete]

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR includes many fix to tweak our UI design

### 🕶️ Types of changes
**Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- [x] ESC to close the Editor if there is no AutoComplete
- [x] Fix the Client autoComplete when there is no clients
- [x] Click outside to close the auto complete
- [x] Fix the Empty State (Explanation at https://github.com/toggl/toggldesktop/issues/2980#issuecomment-496152065)

### 👫 Relationships
Close #2980 

### 🔎 Review hints
- Review all criteria in #2980

### CODE REVIEW

**Comment by IndrekV** [comment]
Good job so far @NghiaTranUIT 

Some more issues:
- [ ] ESC does not close the popup when non-autocomplete items are in focus. (duration, date, start, end time) It should always close the popup when none of the autocomplete dropdowns are opened.
- [ ] When moving around in the edit popup using TAB you cannot start typing into tags field. Only after clicking with mouse on the tags field (button) the dropdown with filter opens and you can type start typing the filter.
- [ ] Autocomplete still not closing in the main window when clicking on the dark overlay

**Comment by IndrekV** [comment]
Just to specify more. Regardles sof the focused element ESC should be closing the popup. If possible it would make sense to have the popupview observe the key event and handle it if appropriate othervise the key event populates to the subitems. Please try to tab between all the elements and test if ESC works and closes the popup. This means all elements. Event the `Delete` button focused and ESC clicked should work.

**Comment by NghiaTranUIT** [comment]
## TagToken with Tab focus
- Able to open Tag AutoComplete when focusing on TagToken by pressing Space
- Able to move the focus around the TagToken

### There is no tags
Focus Ring will move from ... -> Project TextField -> Add Tag button -> Duration -> ...
### Has one tag
From ... -> Project TextField -> This Tag Token  -> Duration -> ...
### Has more tags
From ... -> Project TextField -> First TagToken -> Second ... -> Last  -> Duration -> ...
### GIF

**Comment by NghiaTranUIT** [comment]
@IndrekV this PR is ready for reviewing 👍 Thank for a lot of useful feedbacks to help me push the Editor forward 🥇

**Comment by IndrekV** [comment]
Nice job. Everything in this PR seems to be done! 👍

**Pull request merged**
