### PR TITLE
Linux platforminfo

### LINKED ISSUE #2678: Track windows managers used
### 💻 Environment

Platform: Linux

### 📒 Description
To support the most used window managers we need to track what our users use so we have data to make decisions on

### PR DESCRIPTION
**Pull request by MartinBriza**
### 📒 Description
This is just for a partial code-review of how things are/are to be done for more user statistics in Linux.
I need further guidance and/or help with implementing this into the current analytics code. Feel free to commit directly to this branch 

### 🕶️ Types of changes
- **New feature** (non-breaking change which adds functionality)

### 👫 Relationships
Will close #2678

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
@MartinBriza It would be great if we outline what should we do next in this PR in more detail, then I'm keen to contribute this PR 😄 

It should be a check list ✅ or something

**Comment by MartinBriza** [comment]
Well, this is for @IndrekV mostly - I don't know how to add new metrics into our analytics, i'm not sure what to put on a checklist :D

**Comment by IndrekV** [comment]
I think the call should be made from `context.cc`. And then we can send the data to analytics similar to how we track `channel` https://github.com/toggl/toggldesktop/blob/master/src/context.cc#L286

Todo:
- Create new method to `analytics.cc` that accepts `platfrominfo`
- Track window manager in `Context::StartEvents()` method
- Get window manager data from platforminfo
- Send info to analytics_.TrackWindowManager

The code should have LINUX conditional definition.


One idea I had is that it can be part of the os data we track. Linux just has more os data then other platforms. But it kind of seems to be putting too much data into one analytics item.

**Comment by NghiaTranUIT** [comment]
@MartinBriza Just wondering that this PR is ready for reviewing, isn't it? On the top of that, please update the Review Hint, then we could proceed 👍

**Comment by MartinBriza** [comment]
As I mentioned, I don't know how to review this. I hoped for @IndrekV 's guidance.

**Comment by IndrekV** [comment]
Bugsnag gets the correct data. That means than platform info fetching and sending to Bugsnag works ok. I'm still testing to see if the analytics data sending work and appears online.

**Comment by IndrekV** [comment]
Analytics data appeared and everything works.

**Pull request merged**
