### PR TITLE
Time Reminder issue

### LINKED ISSUE #2692: When editing tracking reminder time the reminder time counter should be reset
### 💻 Environment
Platform: macOS (but it's in library so probably affects all platforms)
Toggl Version: master

### 🐞 Actual behavior
When you have not tracked for at least 1 minute and go to Toggl Desktop settings and change the reminder minutes to 1 minute it will show you a notification right away.

### 💯 Expected behavior
When reminder time is changed the timer should be reset and the notification should come 1 minute later (if setting is 1 minute)

### 🔨 Steps to reproduce

1. Open Toggl
2. Don't track anything for about 2 minutes
3. Go to settings and set Tracking reminder to 1 minute
4. App shows notification right away

### 📦 Additional info
No additional info

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
Whenever we update the time reminder value in Reference, it's critical to reset the last tracking time.

### 🕶️ Types of changes
 **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- [x] Reset `last_tracking_reminder_time_` whenever we update the reminder value.
- [x] Introduce helper `resetLastTrackingReminderTime` to respect DRY.
- [x] Windows version works well.

### 👫 Relationships
Closes #2692 

### 🔎 Review hints
- Checkout master and this PR, then follow "Steps to replicate" in the ticket
- If it's gone => 💯

### CODE REVIEW

**Comment by IndrekV** [comment]
☝️
It seems that comments with reviews are not transferred with our integration.

**Comment by NghiaTranUIT** [comment]
Good point 💪 I totally forgot this case when enabling/disabling this checkbox.

**Comment by NghiaTranUIT** [comment]
@IndrekV It's good now 💯

**Comment by IndrekV** [comment]
All good!

**Pull request merged**
