### PR TITLE
Timeline: Tab view selection

### LINKED ISSUE #3015: Timeline UI - View selection tabs
### 💻 Environment
Platform: macOS

### 📒 Description

- The tabs view is attached to the top timer view
- There are 2 tabs: List and Timeline
- Both items are tabbable
- Active item text is black, non-active item is light grey
- Switching between items will just hide one view and show the other

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR introduces new layout and logic for the Tab View Selection.

### 🕶️ Types of changes
 **New feature** (non-breaking change which adds functionality)

### 🤯 List of changes
- [x] Introduce MainDashboardViewController, which contains "Time Entry List", "Timer Bar" and "Timeline View"
- [x] Stylish the TabView buttons
- [x] Bundle TimeEntryList and Timeline as a TabView
 
### 👫 Relationships
Close #3015 
Parent #3032 

### 🔎 Review hints
- The design should be meet
- Able to switch between Timeline and Time Entry List
- Switch dark/light mode will update the UI

### Screenshots
Screen Shot 2019-06-17 at 17 25 52

### CODE REVIEW

**Comment by skel35** [comment]
Switching between List and Timeline tabs looks good.
I've found a small problem, I can't open the edit popup for the 2nd time, both for finished and for running entries. After the edit popup is hidden, I can open it only after I open another edit popup.
cannoteditentrysecondtime

**Comment by NghiaTranUIT** [comment]
Thank @skel35. I investigated this issue and it turned out that it initially happens in https://github.com/toggl/toggldesktop/pull/3032 too.

I will check it out 👍

**Comment by NghiaTranUIT** [comment]
@skel35 I've fixed this issue at https://github.com/toggl/toggldesktop/commit/9ca209f4b493fee8ea76e3b68200591a2138bd8c from parent branch. I also **rebased** this branch successfully. 

Please checkout on origin and test again. All works now 👍

**Comment by NghiaTranUIT** [comment]
Thank for the feedback @skel35, I would like to cumulate all minor UI improvements and create new ticket for it. The main goal of those PR is fulfilling the requirement of the ticket 👍 

I will do it soon.

**Pull request merged**
