### PR TITLE
Global Toggl Touch Bar

### LINKED ISSUE #3349: Mac Touch Bar - Add global button to Touch Bar
### 💻 Environment

Platform: macOS

### 📒 Description

**Design:**
- Add preference `Show Toggl in Touch Bar`
- This setting should be visible **only** with systems that have touch bar support.
- If the setting is enabled a Toggl touch bar button is added to the touch bar when Toggl Desktop starts and removed when the app closes.
- The touch bar button changes state based on if the timer is running or not.

**Functionality:**
The global button shows the same state as the menubar icon. Pressing the button will either start or stop the timer based on the current status. (This is the basic functionality. If possible we will extend this in version 2 of Touch Bar implementation)

Connected to: #2388

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR introduces the Global Toggl on Touch Bar.

### 🕶️ Types of changes
**New feature** (non-breaking change which adds functionality)

### 🤯 List of changes
- [x] Introduce GlobalTouchBarButton on Control Strip (The right panel)
- [x] Introduce show_touch_bar in library (database and migration)
- [x] Get / set show_touch_bar in library
- [x] Add "Show Toggl in Touch Bar" in Preference. Hide if OS X < 10.12.2
- [x] Start / Stop the TimeEntry when tapping on this global button

### 👫 Relationships
Close #3349 

#### Prepare 
- If your macbook has Touch Bar, it's good news
- If not, please open the Touch Bar Simulator at Xcode app -> Windows Menu -> Show Touch Bar

#### The Global button state is matching the current TE state
1. Start app
2. Check if the Global button is shown -> 💯 
Screen Shot 2019-09-30 at 20 20 43
3. Start the TE on app -> Global btn change to ON icon -> 💯 
4. Stop the TE on app -> Global Btn change to OFF icon -> 💯 
5. Tap on Global btn -> Start or Stop the TE -> 💯 

#### Preference 
1. Open Preference
2. Un-check the "Show Toggl touch bar"
3. The Global btn disappears -> 💯 
4. Stop app
5. Open again and verify that the state is persisted -> 💯

### CODE REVIEW

**Comment by IndrekV** [comment]
On first start the setting is enabled but touch bar icon is not shown. it's probably something to do with the settings being loaded later that he touchbar setting is checked. If I disable and then re-enable the setting icon appears in touch bar. Functionality seemed to be working ok once the icon is shown.

Screenshot 2019-10-08 at 12 51 22

**Comment by NghiaTranUIT** [comment]
Thank for the feedback. 

Unfortunately, I couldn't reproduce it for some reasons.

Here is how I simulate the first launch:
1. Open Production Toggl (7.4.1023) and Clear cache
2. Open `/Users/<your_username>/Library/Application Support/Kopsik/production/kopsik.db`
3. Make sure there is no show_toolbar in the Setting Table
Screen Shot 2019-10-09 at 14 09 14

- If there is this column, please delete this database and open the app again -> It will generate the new local database.

4. Checkout this branch (Please remove the local one since I rebased it)
5. Select Toggl-Production Scheme or select Production mode and run
6. Run the build and check the Touch Bar -> It appears 💯 
7. Check Preference -> Show Toggl Touch Bar is ticked 💯 

Screen Shot 2019-10-09 at 14 10 14

8. Check the database again, and see the `show_touch_bar` is `1` 💯 
Screen Shot 2019-10-09 at 14 10 29

## Codebase
- The default value of `show_touch_bar` is true
https://github.com/toggl/toggldesktop/blob/46b6cf625c91a10fc34ed1de06b26dd71b8e53a6/src/settings.h#L48
- `show_touch_bar ` is 1 on Database Migration phase
https://github.com/toggl/toggldesktop/blob/46b6cf625c91a10fc34ed1de06b26dd71b8e53a6/src/migrations.cc#L1296-L1298
- Load setting and load `show_touch_bar`
https://github.com/toggl/toggldesktop/blob/46b6cf625c91a10fc34ed1de06b26dd71b8e53a6/src/database.cc#L453

I'm not sure what's I'm missing 🤔 

# Suggestion
@skel35 can you run the PR on your machine, since it's complete new environment.
- You can follow the above steps with Production build
- Or you can run on Debug mode as usual. Just run the app and check if the Touch Bar appears or not? If not, please try open the development database at `/Users/<your_username>/Library/Application Support/Kopsik/development/kopsik.db` and check the `show_touch_bar` in the Setting table.

**Comment by IndrekV** [comment]
I tested again and it worked ok. Tested with no database where new database was generated and with an old database where a new field was added to the database table. Everything worked.

**Comment by NghiaTranUIT** [comment]
If we're happy with it, please merge, then I would rebase https://github.com/toggl/toggldesktop/pull/3424 and continue my work 🌮

**Pull request merged**
