### PR TITLE
Work around notification issues on systems without org.freedesktop.Notifications

### LINKED ISSUE #2916: Reminder tab disabled on elementary OS 5.0
### 💻 Environment

Platform: Linux
OS Version: elementary OS 5.0 juno
Toggl Version: About says 7.0.0 but I downloaded a Linux build tagged 7.4.409.

### 🐞 Actual behavior

In Preferences, when I click at the Reminder tab I get the message below overlayed on top of the controls, rendering all the everything unclickable.

> Notifications are not available on your system. You do not have a notification daemon running.

### 💯 Expected behavior

I expected the tab to be fully operational. I wanted to enable the "Remind to track time" feature since I keep forgetting to track time. 😬️

### 🔨 Steps to reproduce

1. Install build 7.4.409 of Toggl for Linux (deb package) on elementary OS.
2. Open Toggle.
3. Click Toggl Desktop > Preferences > Reminder.

### 📦 Additional info

Screenshot from 2019-04-13 18 46 45

### PR DESCRIPTION
**Pull request by MartinBriza**
### 📒 Description
We're doing notifications manually using the DBus freedesktop API so we can handle icons and buttons ourselves. On some platforms (Elementary seems to be the case) this is not available, so this patch makes use of the built-in Qt notification capabilities to work around this.

### 🕶️ Types of changes
- **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- Notification support on Linux is broader

### 👫 Relationships
Closes #2916

### 🔎 Review hints
Test if notifications work on Elementary and some other platform (like GNOME in Ubuntu for example), both.

### CODE REVIEW

**Comment by MartinBriza** [comment]
Ah, I just used `push`, not `push -f` yesterday and didn't notice it failed, sorry.

**Comment by IndrekV** [comment]
Building with cmake fails. Error message:
```
/home/indrek/toggldesktop/src/ui/linux/TogglDesktop/preferencesdialog.cpp: In constructor ‘PreferencesDialog::PreferencesDialog(QWidget*)’:
/home/indrek/toggldesktop/src/ui/linux/TogglDesktop/preferencesdialog.cpp:13:9: error: ‘class Ui::PreferencesDialog’ has no member named ‘reminderWarning’; did you mean ‘reminderMinutes’?
     ui->reminderWarning->setGeometry(ui->tab_reminder->geometry());
         ^~~~~~~~~~~~~~~
         reminderMinutes
/home/indrek/toggldesktop/src/ui/linux/TogglDesktop/preferencesdialog.cpp: In member function ‘virtual void PreferencesDialog::paintEvent(QPaintEvent*)’:
/home/indrek/toggldesktop/src/ui/linux/TogglDesktop/preferencesdialog.cpp:301:9: error: ‘class Ui::PreferencesDialog’ has no member named ‘reminderWarning’; did you mean ‘reminderMinutes’?
     ui->reminderWarning->setGeometry(ui->tab_reminder->geometry());
         ^~~~~~~~~~~~~~~
         reminderMinutes
```

**Comment by MartinBriza** [comment]
Should be fixed already, while you were writing the comment, I'm sorry for the trouble.

**Comment by IndrekV** [comment]
Tested on Pantheon (Elementary OS) and Gnome and it works. And the notifications look very good actually. We should add similar workarounds to other notifications as well (Idle for example)

**Pull request merged**
