### PR TITLE
[WIP] Timeline: Header

### LINKED ISSUE #3016: Timeline U - header
### 💻 Environment
Platform: macOS

### 📒 Description

Timeline view header has 2 components:
- Record activity switch to turn timeline tracking on and off
- Date Picker. This should be the same component used in edit view with the exception that calendar popup *cannot* be opened (reason being that we only show about 9 days of data to the user and there is no need to have a fully functional calendar view here). Left / Right arrows move the day forward or backward. 

Connected to #2890

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR will introduce the Header for Timeline feature.

### 🕶️ Types of changes
 **New feature** (non-breaking change which adds functionality)

### 🤯 List of changes
- [x] Convert DatePickerView from Editor to be dependency
- [x] Reuse DatePickerView for Header
- [x] Navigate through controls by hitting "Tab"
- [x] Logic to enable/disable Timeline Recorder (same logic in Preference) 
- [x] Adopt OCSwitch, since Cocoa doesn't have native Switcher

### 👫 Relationships
Closes #3016 

### 🔎 Review hints
- Same UI with designs
- The Recorder Switcher is matching with the Timeline Recorder in Preference. Ex: If we enable in Preference -> The Switcher should turn ON and vice versa.

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
## Known-issues:
https://github.com/toggl/toggldesktop/issues/3016#issuecomment-503028389

**Comment by NghiaTranUIT** [comment]
@skel35 The logic for Data Change in Header hasn't been ready for implementing yet. So I will move all logic to next PR, which is "Timeline: Global View"

**Comment by IndrekV** [comment]
I'm unable to build this. I get an error:
```
Showing Recent Messages
:-1: Build input files cannot be found: '/Users/indrekv/projects/toggldesktop/src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/Key.swift', '/Users/indrekv/projects/toggldesktop/src/ui/osx/TogglDesktop/Feature/Calendar/CalendarCollectionView.swift', '/Users/indrekv/projects/toggldesktop/src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/ResizablePopover.swift', '/Users/indrekv/projects/toggldesktop/src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/AddTagButton.swift'
```

I cleaned the project and rebuilt but same issue is coming up

**Comment by NghiaTranUIT** [comment]
@IndrekV I suggest that we should review this https://github.com/toggl/toggldesktop/pull/3050, since it's including the fix and many changes for this PR.

**Comment by skel35** [comment]
The mentioned issues were mostly addressed in #3050. 
What's left:
- [ ] Date picker should have a white background
- [ ] Clicking on a date should pop up the calendar

**Pull request merged**
