### PR TITLE
Upgrade Swift 5 and Xcode 10.2

### LINKED ISSUE #2896: Unable to build source code in Xcode 10.2
After upgrading to Xcode 10.2, we are unable to run or archive the app anymore because of the new syntax of Swift 5.

### 💻 Environment
Platform: macOS
OS Version: macOS 10.14.2
Toggl Version: in master`

### 🐞 Actual behavior
- Unable to build app due to the new syntax of Swift 5, which is built-in in Xcode 10.2 

### 💯 Expected behavior
- Should be able to run and archive/

### 🔨 Steps to reproduce
1. Upgrade Xcode 10.2
2. Start the project in master branch

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR will introduce the Swift 5.0 upgrade, which is crucial factor to be able run on Xcode 10.2

### 🕶️ Types of changes
 **Improvements** (non-breaking change which adds functionality)

### 🤯 List of changes
- [x] Upgrade the Swift codebase to Swift 5
- [x] Update recommended Xcode config for TogglDesktop and TogglDesktopLibrary
- [x] Downloaded the Xcode 10.2 and prepare the process on mini-bot 🤖 

### 👫 Relationships
Close #2896 

### 🔎 Review hints
- Able to build on Xcode 10.2 in local workspace and mini-bot

### CODE REVIEW

**Comment by IndrekV** [comment]
Will Swift 5 work with macos 10.11?

**Comment by NghiaTranUIT** [comment]
Good question. Theoretically, It still able to run on macOS 10.11.

I will archive the build and double check on my OS 10.11 Parallels 👍

**Comment by NghiaTranUIT** [comment]
## Result 
1. It is able to run on macOS 10.11
Screen Shot 2019-05-15 at 3 10 38 PM
Screen Shot 2019-05-15 at 3 10 59 PM

2. There is blank empty screen after doing a hack to avoid the conflict between textColor in `FlatButton` with objc-setter in Xcode 10.2 (the bug only occurs when archiving the app). This issue is fixed in https://github.com/toggl/toggldesktop/pull/2953/commits/4413eafdbcc2d0fb5b77bbed26335888181d6ad3

**Comment by MartinBriza** [comment]
From my point of view, everything is OK. However, I don't understand a lot of what's going on in here so I think it's best to leave the ultimate decision on this to @IndrekV

**Comment by NghiaTranUIT** [comment]
Yup, upgrade to Swift 5 and Xcode 10.2 doesn't affect much the app. One thing should be concern is that we have to upgrade to Xcode 10.2 in mini-bot too (Which I already downloaded it in ~/Application).

And set Xcode 10.2 in **Preferences**. So the `xcodebuild` will use correct version.

Screen Shot 2019-06-27 at 15 56 20

**Comment by IndrekV** [comment]
I tested it with Xcode 10.2 and everything seems to be working ok. I want to build one more release in the buildbot and then we can update Xcode can merge this PR.

**Comment by skel35** [comment]
The beta was built yesterday, I think we can finally merge this PR, 🍏 guys

**Comment by NghiaTranUIT** [comment]
Just rebased from master. 

The failure was that this PR is out of date (Missing Bugsnag PR from master), but the build script in toggl-branding has the new update (Code-sign for Bugsnag framework).

I'm testing and will inform when it's done 👍

**Pull request merged**
