### PR TITLE
Fixed toggl_api.h format so csapi generation would work

### PR DESCRIPTION
**Pull request by IndrekV**
### 📒 Description
Fixes the file generation forTogglApi.cs 

### 🕶️ Types of changes

**Bug fix** (non-breaking change which fixes an issue)

### 🔎 Review hints
When building TogglApi should not show any errors.

### CODE REVIEW

**Comment by MartinBriza** [comment]
I think you based this branch on a branch that's not `master`, there are some unrelated commits at the beginning

**Comment by IndrekV** [comment]
you are right

**Comment by IndrekV** [comment]
Should be fixed now

**Comment by IndrekV** [comment]
Now it should build just fine. Please review @skel35 this and merge if it works for you too.

**Pull request merged**
