### PR TITLE
New design for Autocomplete in TimerBar

### LINKED ISSUE #2814: New design for Auto Complete
### 📒 Description
The design for Auto Complete is done. It's time to do it 👍 

### 💻 Environment
Platform: macOS

### 💯 Acceptance Criteria 
- Implement the design for Auto Complete
- Maintain the original logic
- Make sure it works in Edit Entry

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
## ⚠️ Warning 
- This PR is branched off from #2844, so it's critical to merge it before reviewing in this PR 🍰 

### 📒 Description
- This PR dedicatedly introduce new design for Timer Bar and keep maintaining the original logic for AutoComplete in Edit Time Entry Popover. As the design is totally different and should be in separate ticket 🎫 

### 🕶️ Types of changes
**New feature** (non-breaking change which adds functionality) 

### 🤯 List of changes
- [x] Refactor how AutoComplete feature works (Refactor code, re-use ProjectLabel components, fix bug and improve the logic to calculate the height of AutoCompleteContainer, ...)
- [x] Implement new design

### 👫 Relationships
Closes #2814 

### 🔎 Review hints
- Test fully all case of AutoComplete and make sure it works 💯

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
Rebased this PR from #2844

**Comment by IndrekV** [comment]
I fixed the issue where the color of project name dot was wrong. Also there was an issue that client dot was visible when there was no client added to the time entry.

timer

Currently the focus ring looks very strange and doesn't fit the timer design. Is it possible to make the focus ring to be similar to the input field design (bigger corner radius). Might be possible with someting like https://stackoverflow.com/a/10569801/1015296

timer_focus

**Comment by IndrekV** [comment]
Autocomplete does not have a bottom constraint and when window has smaller height the bottom of the listing is outside of the view.

Screenshot 2019-03-25 at 14 37 08

**Comment by NghiaTranUIT** [comment]
It's ready to review in second phrase. Please make sure to check out new branch from origin since I've rebased it 👍

**Pull request merged**
