### PR TITLE
Add Windows Application Packaging Project to our solution

### LINKED ISSUE #3044: Add Windows Application Packaging Project to our build cycle
### 💻 Environment
Platform: Windows

### 📒 Description
[Windows Application Packaging Project](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net) is currently a recommended way to package Win32 apps to Microsoft Store as it gives the most flexibility and ease of use.

Below is a rough list of things that need to be done in order to make an MS Store release using Win App Packaging Project:

- [x] #3090 Update target .NET Framework version to 4.6.1
- [x] #3057 Install VS 2017 15.5 or newer build tools on the build agent(s) and change the script to use corresponding MSBuild (will also enable us to switch the C++ projects to target newer MSVC Toolset)
- [x] #3090 Add Windows Application Packaging Project to the solution
- [x] #3090 Make sure C++ DLLs are copied to a proper output folder for MS Store build
- [x] #3090 Disable our existing auto-update functionality for MS Store version
- [x] #3090 Make sure MSVC++ redistributable is properly bundled (either that existing method of bundling DLLs works or that dependency on MSVC++ UWP package is set up)
- [x] #3090 Add icons for all necessary sizes
- (Partially done, will reconsider icons after the rebranding) Make icons with a design suited to MS Store applications
- (Moved to #3111) Utilize live tiles to visualize the current state of the timer, remind to track, etc.

### ⭐️ Why do you want this?
The goal is to add Toggl Desktop to Microsoft Store. See #2203.

### PR DESCRIPTION
**Pull request by skel35**
### 📒 Description
Adds Windows Application Packaging Project to our solution.
Makes it possible to build a UWP package which can be released.
Makes it possible to run a UWP version from the IDE.

### 🕶️ Types of changes
**New feature** (non-breaking change which adds functionality)

### 🤯 List of changes
- [x] Add Windows Application Packaging Project to the solution
- [x] Make sure C++ DLLs are copied to a proper output folder for MS Store build
- [x] Make sure MSVC++ redistributable is properly bundled
- [x] Disable our existing auto-update functionality for MS Store version
- [x] Add icons for all necessary sizes, prettify stuff

What's left to do in order to be able to release:
- Set up MS Store account
- Upload the app to the store and pass verification

### 👫 Relationships
Closes #3044

### 🔎 Review hints

- Run from Visual Studio
  - StoreDebug (staging) or StoreRelease (production) config
  - Right-click `TogglDesktop.Package` ->Set as StartUp Project
  - Press F5
  - UWP version of Toggl Desktop should be running

- Build an entire `appxupload` file which includes both x86 and x64 versions bundled with all dependencies and ready to be uploaded to MS Store.
  - Run the following 2 commands from repo folder:
  - `MSBuild.exe src/ui/windows/TogglDesktop/TogglDesktop.sln /p:Configuration=StoreRelease /p:Platform="x86" /t:Clean,Build /restore /p:AppxPackageSigningEnabled=false -m`
  - `MSBuild.exe src/ui/windows/TogglDesktop/TogglDesktop.sln /p:Configuration=StoreRelease /p:Platform="x64" /p:PackageCertificateKeyFile="..\..\..\..\branding\windows\Toggl.pfx" /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64" /t:Clean,Build /restore -m`
  - see `src\ui\windows\TogglDesktop\TogglDesktop.Package\AppPackages` which now contains `.appxupload` file which can be uploaded to MS Store. Open it as a zip file to view its contents (nested `.appxbundle` files can also be open as zip files)
  - Double-click `.appxbundle` file will install it as a Win10 application. Smoke test that it works as a regular Toggl Desktop app.

### 📔  Notes
https://github.com/toggl/toggldesktop-branding/pull/36

### CODE REVIEW

**Comment by IndrekV** [comment]
It would make sense to also create a script that submits to the store when we move a version to the stable channel.

**Comment by skel35** [comment]
Sure, I'll look into it once we have our account set up

**Comment by skel35** [comment]
Icons for tiles:
Medium tile 
image

Small tile
image

Large tile
image

Wide tile
image

Store listing/installation
image

Start menu item
image

**Comment by skel35** [comment]
All icons are added.
Windows App Certification Test was passed locally, test results attached:
[result.zip](https://github.com/toggl/toggldesktop/files/3417845/result.zip)
The only error is regarding launching external processes which only impacts opening web browser links on Windows 10 S mode, so we can look into later, see #3115.

The app looks fully usable and ready for release testing.
@IndrekV Feel free to review this PR.

**Comment by skel35** [comment]
Just realized there is no need to raise a target .NET Framework version for a regular release build because MSBuild supports setting different versions for different build configurations.

**Pull request merged**
