### PR TITLE
Keyboard on Calendar Editor

### LINKED ISSUE #2982: Total keyboard support for edit popup
### 💻 Environment
Platform: macOS

### 📒 Description
It should be possible to do everything with a keyboard. Some of this is addressed with #2981

One other thing that is currently missing is selecting day from calendar popup using a keyboard.

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
Tiny improvement to support keyboard in Calendar Editor.

### 🕶️ Types of changes
**Improvement** (non-breaking change which adds functionality)

### 🤯 List of changes
- [x] Select the selected date in Calendar in order to make it become first responder. -> Able to navigate around by keyboard.

### 👫 Relationships
Close #2982 

### 🔎 Review hints
- After the Calendar pop-up, we could select dates by keyboard => 💯

### CODE REVIEW

**Comment by IndrekV** [comment]
Currently opening calendar popup only works with pressing space when the day name is selected. It is kind of confusing. I think it would make sense to always open the popup when one of the date fields is focused and user presses SPACE.

Selecting date should happen when pressind ENTER or SPACE. Currently pressing ESC works but I don't think it's very obvisous that ESC is saving things.

**Comment by NghiaTranUIT** [comment]
It totally make scene. I'd improve by following your suggestion 👍

**Comment by NghiaTranUIT** [comment]
I've updated new logic for 
- Navigating around the Calendar by keyboard and the selecting action would execute only when pressing the Enter, Space and mouse. 
- Escape key will close and ignore the selection.
- Space on DatePicker's fields will open Calendar.



Ready for review @IndrekV 🌮

**Comment by IndrekV** [comment]
Nicely done, now everything seems to be working perfectly. Great job Nghia! 👍

**Pull request merged**
