### PR TITLE
New design for Timer Bar

### LINKED ISSUE #2843: Timer Bar new design
### 📒 Description
It's time to implement the new design for Timer Bar.

### 💻 Environment
Platform: macOS

### 💯 Acceptance Criteria 
- Implement the design for Timer Bar
- Maintain the original logic

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### ⚠️ Warning
This PR is branched off from #2815, so it's crucial to merge it before proceeding.
@NghiaTranUIT will be in charge of rebasing this branch when the #2815 is merged 👍 .

### 📒 Description
This PR will introduce the new design for Timer Bar.

### 🕶️ Types of changes
 **New feature** (non-breaking change which adds functionality

### 🤯 List of changes
- [x] Implement new design for Timer Bar
- [x] Customize the Focus Ring of AutoCompleteInput in Timer Bar to fit with the design
- [x] Refactor the structure of Timer bar and the logic to layout
- [x] Reuse several parts from #2815 to render Project (AttributeString, Color, ..)
- [x] Basic Improvements

### 👫 Relationships
Close #2843 

### 🔎 Review hints
- Make sure the logic is remain

### Note 📓 
There is known-issues (#2833), which cause the focus is jump-ping unexpectedly in someway.

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
## BetterFocusInputAutocompleteView
- Basically, this PR introduce this class `BetterFocusInputAutocompleteView`, which is subclassed from `InputAutocompleteView` in order to implement the design of app.
- Technically, it also receives the state of its responder and send to the outsider to apply proper layout.
- It also overrides the frame of Focus Ring 
- Because it's inheritance, so it doesn't affect to different instance in app. So it's safer.

**Comment by NghiaTranUIT** [comment]
Just rebased, but it has some problem when selecting the cell. I'm investigating it 🔬

**Comment by NghiaTranUIT** [comment]
It's ready for reviewing after #2815 👍

**Comment by NghiaTranUIT** [comment]
It's ready for reviewing 👍

**Comment by IndrekV** [comment]
I fixed the issue where the color of project name dot was wrong. Also there was an issue that client dot was visible when there was no client added to the time entry.

timer

Currently the focus ring looks very strange and doesn't fit the timer design. Is it possible to make the focus ring to be similar to the input field design (bigger corner radius). Might be possible with someting like https://stackoverflow.com/a/10569801/1015296

timer_focus

**Comment by NghiaTranUIT** [comment]
I have to override the -focusRingDraw method to be able to draw the corner rounded Focus Ring at https://github.com/toggl/toggldesktop/pull/2844/commits/1913cec08cd64aac49fcb626f985cfaa3bf7d9dc

The `VerticallyCenteredTextFieldCell` class is what I've done during working on Project Text Field in Editor Popover, so I reuse it here 👍 

It's also ready to review.

**Comment by IndrekV** [comment]
Well done with shaping the focus ring. I'm really impressed.

Another issue that I came across. When you select project from autocomplete it does not show the selected project anywhere. In the old solution a project view would be visible and the input would be move a bit up. I'm not sure there was a design for this, but we should find a solution.

**Comment by IndrekV** [comment]
A gif to illustrate my last comment

mac_project_select

**Pull request merged**
