### PR TITLE
Upgrade Poco 1.9.0

### LINKED ISSUE #2285: Update poco to most recent stable release
Packaged poco is dated. #2279

### LINKED ISSUE #2532: App crashing on shutdown
App seems to be crashing in some cases.

ic: 17700239842

**App info**
```
OS Version: Mac OS X 10.12.6 (16G1314)
Version: 7.4.231 (7.4.231)
```
**Exception**
```
Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000229
Exception Note: EXC_CORPSE_NOTIFY
```
**Crashlog**
```

Thread 1 Crashed:

0 TogglDesktopLibrary.dylib 0x000000010542a88c toggl::User::LoadUserPreferencesFromJSON(Json::Value) + 58

1 TogglDesktopLibrary.dylib 0x000000010548589f toggl::Context::pullUserPreferences(toggl::TogglClient*) + 1269

2 TogglDesktopLibrary.dylib 0x0000000105475687 toggl::Context::pullAllUserData(toggl::TogglClient*) + 1475

3 TogglDesktopLibrary.dylib 0x0000000105474a99 toggl::Context::onSync(Poco::Util::TimerTask&) + 515

4 libPocoUtil.50.dylib 0x00000001059bf1e9 Poco::Util::TaskNotification::execute() + 57

5 libPocoUtil.50.dylib 0x00000001059bed89 Poco::Util::Timer::run() + 57

6 libPocoFoundation.50.dylib 0x0000000105e10eb7 Poco::ThreadImpl::runnableEntry(void*) + 103

7 libsystem_pthread.dylib 0x00007fffc109793b _pthread_body + 180

8 libsystem_pthread.dylib 0x00007fffc1097887 _pthread_start + 286

9 libsystem_pthread.dylib 0x00007fffc109708d thread_start + 13
```

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
It's the dedicated effort to upgrade our Poco library, which is responsible for certain crashes on Toggl Desktop.

### 🕶️ Types of changes
**Breaking change** (fix or feature that would cause existing functionality to change) 

### 🤯 List of changes
- [x] Delete existing Poco, and paste the latest 1.9.0
- [x] Work on macOS
- [x] Work on Windows
- [x] Work on Linux

### 👫 Relationships
Closes #2532 
Closes #2285

### 🔎 Review hints **(Update)**
1. Clone **freshly** this repo (or `git reset --hard && git clean -fdx` on existing project)
2. Execute successfully "make deps", "make", "make run" in macOS and linux.
3. Able to run app on Windows, VS 2013.
4. Toggl is able to fetch/save the entry list from backend

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
Confirmed that the latest Poco is working well in Linux 💯

**Comment by IndrekV** [comment]
Works ok in mac. I'll look into other platforms.

**Comment by NghiaTranUIT** [comment]
After rebasing from master, this PR works correctly in macOS and linux, with many new changes from master (Sparkle, Cmake, Makefile, ..). I'm looking for testing in Windows platform 👍 

Pls make sure that we delete this local branch then checking out from origin since I rebased and pushed -f 👨‍💻

**Comment by NghiaTranUIT** [comment]
It turns out that our .gitignore discard all files from our poco/openssl, which I clone from https://github.com/pocoproject/openssl/tree/master

https://github.com/toggl/toggldesktop/blob/9ea1df83aa324adfc54e04d01cbee21622dbd17f/.gitignore#L86-L94

I have to remove it in order to build the app successfully with new Poco in Windows. Otherwise, there are wired error when linking library in Crypto.lib.

**Comment by NghiaTranUIT** [comment]
All works are done successfully in all platforms 👍 

We can start to review this ticket again due to certain changes for Windows.

Make sure we delete local branch and fetch the latest on origin 😎

P/S: Updated `Review hint` section.

**Pull request merged**
