### PR TITLE
Sign up with Google on macOS

### LINKED ISSUE #3278: Sign up with Google on macOS
### 💻 Environment
Platform: macOS

### 📒 Description
Add "Sign up with Google" button below the Sign up" button.
To be done after the library part is implemented in #3064.
Obtaining the Google access token is exactly the same as with Google login.

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR introduces the Google Sign-up feature on Login Screen.

### 🕶️ Types of changes
**New feature** (non-breaking change which adds functionality)

### 🤯 List of changes
- [x] Refactor how Validation works
- [x] Support Validate for Google Sign up (Country and TOS check)
- [x] Use async Google Signup from library

### 👫 Relationships
Closes #3278

#### Login with normal account
1. Missing Email -> Show error
2. Missing Password -> Show error
3. Incorrect password -> Show error
4. Correct account -> Go in Main View

### Signup with normal Account
1. Missing Email -> Show error
2. Missing Password -> Show error
3. Missing Country -> Show Error
4. Missing TOS check -> Show Error
5. Correct Account -> Go in Main View

#### Login with Google
1. Able to login google 
2. Click X on Google Panel -> NO error message 

#### Signup with Google
1. Missing Country -> Show error
2. Missing TOS -> Show Error
3. New Account -> Able to sign up
4. Try to sign-in with Existed account -> Show error

### CODE REVIEW

**Comment by IndrekV** [comment]
Is this ready for a review?

**Comment by NghiaTranUIT** [comment]
@IndrekV it's ready for review  👍

**Comment by IndrekV** [comment]
Everything seems to work. It still asks for the credentials every time, but I guess this was handled in another issue.

**Comment by NghiaTranUIT** [comment]
If we review https://github.com/toggl/toggldesktop/pull/3326, TogglDesktop won't ask the credential everytime 😄

**Pull request merged**
