### PR TITLE
New about design

### LINKED ISSUE #2779: New About design
### 📒 Description
It's essential to implement new About screen design since it's been done.

### 💻 Environment
Platform: macOS

### ⭐️ Acceptance Criteria
- Respect the design
- Support light/dark theme

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### 📒 Description
This PR implement new design of About Screen.

### ⚠️ Warning  
This PR is branched off from `New Login and Signup` (#2774) PR because we have to reuse some essential components and assets.

Thus, please make sure we review and merge #2774, then @NghiaTranUIT will be in charge to **rebase** this PR appropriately.

### 🕶️ Types of changes
**New feature** (non-breaking change which adds functionality)

### 🤯 List of changes
- Update new design for About screen
- Remove credit view, since we don't have it in design
- Maintain the current logic
- Adopt dark theme

### 👫 Relationships
Closes #2779 

### 🔎 Review hints
- Same design
- Able to update app.

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
Resolve the conflict too. Pls make sure that the Login and Signup Design (#2774) must be merged firstly 👍

**Comment by IndrekV** [comment]
For some reason the space is missing in `TOGGL DESKTOP`
screenshot 2019-02-06 at 08 48 38

**Comment by NghiaTranUIT** [comment]
@IndrekV It's ready for reviewing 👍

**Comment by IndrekV** [comment]
The button should be visible but disabled at the time of downloading. Also the green button has rounded corners in the design.

**Comment by NghiaTranUIT** [comment]
I've fixed all the Restart Button's func. It's totally ready for proceeding 👍

**Comment by NghiaTranUIT** [comment]
Resolved conflict and fix the bug on Restart button. It's ready for reviewing 👍

**Pull request merged**
