### PR TITLE
Time Entry editor

### PR DESCRIPTION
**Pull request by NghiaTranUIT**
### Description
This PR is a combination of many sub-tickets (See change-logs). Each tickets should be reviewed and approved separately before reviewing in the final round 🚀 

### 🤯 List of changes
It's a big PR for Time Entry Editor. It's also a parent for many following sub-tickets:
- [x] General logic for Popover #2860 
- [x] Project Creation: Generic AutoComplete, AutoComplete for Project, Client, Workspace, basic Color Picker and all relevant logic to fetch them from Library (in-progress) #2857 
- [x] Tag input
- ~[ ] Time Input #2858~ We decided to postpone this ticket until we have the consensus regarding the Clock View 
- [x] Date input #2859 
- [x] Project Color Picker #2856 

### 🕶️ Types of changes
**Breaking change** (fix or feature that would cause existing functionality to change)

### 👫 Relationships
Project (https://github.com/toggl/toggldesktop/projects/1)

### 🔎 Review hints
- All logic is remains
- Double check the designs

### CODE REVIEW

**Comment by NghiaTranUIT** [comment]
Rebased 👍

**Comment by NghiaTranUIT** [comment]
@IndrekV @MartinBriza All sub-tickets are already approved and merged appropriately. 
So, This huge Editor PR is already for reviewing in the final round 👏

**Comment by IndrekV** [comment]
- [ ]  Description field autocomplete does not show any suggestions.
- [ ]  Billable flag checkbox should be visible only when the time entry is in a non-free workspace
- [ ]  Start and end times are cut off. We need to make the edit popup a bit wider to accommodate the values in these fields.
- [ ]  The arrow between the start and stop time should not be focusable with tab.
- [ ]  Editing start or stop time and pressing tab to move to the next field does not update other time fields. Editing duration and pressing tab will update stop time accordingly.

**Additional screenshots**
Empty autocomplete in edit view:
mac-ac-empty

Start and stop time cut off:
cutoff_fields

**Comment by NghiaTranUIT** [comment]
@IndrekV, I've updated new logic for Description AutoComplete as well as resolved few issues, which you mention in last comment 👍 



## Description AutoComplete's capabilities
- Able to Enter to update new Description
- Tab to move to next field & update description
- Search & auto complete
- Select existing Description from keyboard, mouse -> Update Description and Project if need
- Layout for Description Cell: Description Lbl + Color Dot View + Project or Client label

**Comment by IndrekV** [comment]
I added some fixes:
- fixed the start stop field width issue without the render triggering. This render triggering cause the size of the popup to change when the width of fields changed because of the content. New solution sets a fixed with that can always fit the correct format of the time.
- Added "refuse first responder" to the arrow between time fields so it doesn't get focused ever.

All other issues seem to be fixed.

Now for some more tweaks before we can merge this in:

- [ ] Calendar seems slow somehow. There seems to be a delay opening the calendar popup. Also switching days seems to take 1 second to execute.
- [ ] Calendar hover color is gray but should be light green (see Zeplin for the color)
- [ ] Calendar selected date color text should be white not black

Screenshot 2019-05-17 at 11 56 30

- [ ] When you filter tags and then select one of them the list reloads and discards the filter. The list should not reload and should keep the same filtered state after selection.

mac-tags


If these issues are fixed we need to rebase against master and we can go on with merging this in and preparing for the grand release. Good job Nghia with all the implementations!

**Comment by NghiaTranUIT** [comment]
The investigation on unresponsive Calendar when selecting new date, reveals that this following code causes the problem:

https://github.com/toggl/toggldesktop/blob/60a279c33f4e8d74f52153c398147ccf33eff460/src/ui/osx/TogglDesktop/Feature/Calendar/CalendarDataSource.swift#L76

Basically, I calculate the start and end date from the current date, then rendering the Calendar. Each cell will calculate the date by adding the index -> This action burdens the CPU -> 1s delay

I will come up alternative idea to resolve it.

**Comment by NghiaTranUIT** [comment]
@IndrekV this PR is ready for reviewing 👍. I did a merge because I was unable to resolve the conflict when rebasing (git rebase -i master) the huge number of commits in this branch.

## What's news
- Re-implement the Calendar logic to render appropriately without using NSCalendar too much. In the original approach, every time the cell is rendered, it will convert the NSIndexPath to date by using NSCalendar -> It means that it burdens the CPU.

## Better approach
Here is the idea of new approach:
1. Give selected date -> Calculate the first day of week (replies on the First Day of Week in System Preference)
2. Get the `from` date by moving by offset weeks
3. Get the `to` date by adding offset weeks
4. Get the number of day for all months from `from` -> `to` (Use NSCalendar to get correctly since the number of day relies on what kind of years, ....)
4. Calculate all Date struct (consist of day, month, year: Int) by adding 1 day from `from` -> `to` => By this solution, I don't use NSCalendar to construct the NSDate, because it's inefficient-process
5. Flat the map 
6. Render on the Collection View

## Result
- Scrolling is better, no lagging like previous version
- Frozen 1 seconds is gone, however, it isn't disappear completely. Every time we update the Date of Time Entry, there are heavy things are executed in main Thread (Store on db, logic in Library, Reload the TIme Entry cell, calculate the Position of Popover, ...) -> Still lag, but acceptable

**Comment by IndrekV** [comment]
All the issues pointed out are addressed and now work correctly. Good job @NghiaTranUIT !

2 last issues I noticed that are different in old design
When editing a running entry:
- Stop time input should be hidden (as it can not be edited)
- Calendar should be disabled as you can track only right now not in the past or the future

**Comment by IndrekV** [comment]
Ok everything seems in order. Drum roll please..... It's time to merge this bad boy in!

**Pull request merged**
