### PR TITLE
Add CMake as a buildsystem for Linux

### LINKED ISSUE #2687: Use CMake instead of just a Makefile
### 💻 Environment
Platform: Linux and macOS

I suggest applying this to Linux first and to macOS later if this proves to be the right way to go.

### 📒 Description
Current way of building Toggl Desktop is not configurable, cannot use systemwide libraries and takes an insanely long time (about one hour on my Kaby Lake R laptop) without the possibility to build in parallel (`make -j`).

Hence I suggest switching to a different build system - CMake seems to be a good choice for a project of this size and complexity. It will generate Makefiles for us automatically based on the description of the project. It is also completely multiplatform and allows configuring the build process.

I put a basic `CMakeLists.txt` into the `cmake` branch in git to show what a difference it can make. For now, it uses systemwide `poco`, `lua`, `json` and `Qwt` but I'll modify it to let us choose if we want to use systemwide or bundled libraries.

The biggest benefit so far: building the whole project from scratch now takes around 50 seconds on my machine.

### PR DESCRIPTION
**Pull request by MartinBriza**
### 📒 Description
This adds a bunch of CMakeLists.txt files to the project to make building the application easier on Linux (and maybe on other platforms too in the future).
It also makes installing the app properly possible

### 🕶️ Types of changes
- **New feature** (non-breaking change which adds functionality)
- **Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes
- CMakeLists.txt to define the build
- App metadata files for linux
- Slight improvement to TogglDesktop.sh

Our CMakeLists.txt has optional arguments: 
- `-DTOGGL_VERSION="7.0.0"` to define the version of the app
- `-DTOGGL_PRODUCTION_BUILD=ON` to switch to a production release
- `-DTOGGL_ALLOW_UPDATE_CHECK=ON` to allow update checks
- `-DUSE_BUNDLED_LIBRARIES=ON` to let the app use systemwide library variants (Poco, Lua, Qxt, JSON) instead of the ones in the `third_party` directory

In addition there are CMake standard arguments like:
- `-DCMAKE_INSTALL_PREFIX=/some/path` will make `make install` install the app into `/some/path/bin`, `/some/path/lib`, etc. 

### 👫 Relationships
This PR has a counterpart in the Branding repository.

** Depends on #2696 ** 

Closes #2687 

### 🔎 Review hints 
The usual build process looks like this:
```
# in the toggldesktop source tree root
mkdir -p build && pushd build
cmake ..                         # append optional arguments as defined above
make -j8                         # the number defines the count of parallel jobs (number of your CPU cores is a good value for that)
make install                     # optional, will install the app and libraries into /usr/local if CMAKE_INSTALL_PREFIX is not defined
popd build
```

### CODE REVIEW

**Comment by MartinBriza** [comment]
Also, don't merge yet, I'll squash the commits first, 23 is too much

**Comment by IndrekV** [comment]
I'm getting these errors when running `make -j8`

```
/home/osboxes/toggldesktop/third_party/qxtglobalshortcut5/gui/qxtglobalshortcut_x11.cpp:37:45: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
 #   include <qpa/qplatformnativeinterface.h>
                                             ^
compilation terminated.
third_party/CMakeFiles/Qxt.dir/build.make:86: recipe for target 'third_party/CMakeFiles/Qxt.dir/qxtglobalshortcut5/gui/qxtglobalshortcut_x11.cpp.o' failed
make[2]: *** [third_party/CMakeFiles/Qxt.dir/qxtglobalshortcut5/gui/qxtglobalshortcut_x11.cpp.o] Error 1
CMakeFiles/Makefile2:211: recipe for target 'third_party/CMakeFiles/Qxt.dir/all' failed
make[1]: *** [third_party/CMakeFiles/Qxt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/qwebengineview.h:48:0,
                 from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/QWebEngineView:1,
                 from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/ui_logindialog.h:20,
                 from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/logindialog.cpp:2:
/home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/qwebenginepage.h:251:14: error: missing binary operator before token "("
 #if QT_CONFIG(menu)
              ^
In file included from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/QWebEngineView:1:0,
                 from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/ui_logindialog.h:20,
                 from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/logindialog.cpp:2:
/home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/qwebengineview.h:123:14: error: missing binary operator before token "("
 #if QT_CONFIG(contextmenu)
              ^
/home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/qwebengineview.h:129:14: error: missing binary operator before token "("
 #if QT_CONFIG(draganddrop)
              ^
In file included from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/qwebenginepage.h:46:0,
                 from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/qwebengineview.h:48,
                 from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/QWebEngineView:1,
                 from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/ui_logindialog.h:20,
                 from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/logindialog.cpp:2:
/home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineCore/qwebenginecallback.h:96:1: error: expected constructor, destructor, or type conversion before ‘Q_DECLARE_SHARED_NOT_MOVABLE_UNTIL_QT6’
 Q_DECLARE_SHARED_NOT_MOVABLE_UNTIL_QT6(QWebEngineCallback<const QString &>)
 ^
In file included from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/qwebenginepage.h:47:0,
                 from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/qwebengineview.h:48,
                 from /home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineWidgets/QWebEngineView:1,
                 from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/ui_logindialog.h:20,
                 from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/logindialog.cpp:2:
/home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineCore/qwebenginehttprequest.h:97:24: error: ‘QWebEngineHttpRequestPrivate’ was not declared in this scope
     QSharedDataPointer<QWebEngineHttpRequestPrivate> d;
                        ^
/home/osboxes/Qt/5.12.0/gcc_64/include/QtWebEngineCore/qwebenginehttprequest.h:97:52: error: template argument 1 is invalid
     QSharedDataPointer<QWebEngineHttpRequestPrivate> d;
                                                    ^
In file included from /home/osboxes/toggldesktop/third_party/qt-oauth-lib/logindialog.cpp:2:0:
/home/osboxes/toggldesktop/third_party/qt-oauth-lib/ui_logindialog.h: In member function ‘void Ui_LoginDialog::retranslateUi(QDialog*)’:
/home/osboxes/toggldesktop/third_party/qt-oauth-lib/ui_logindialog.h:61:92: error: ‘nullptr’ was not declared in this scope
         LoginDialog->setWindowTitle(QApplication::translate("LoginDialog", "Login Dialog", nullptr));
                                                                                            ^
third_party/CMakeFiles/OAuth2.dir/build.make:62: recipe for target 'third_party/CMakeFiles/OAuth2.dir/qt-oauth-lib/logindialog.cpp.o' failed
make[2]: *** [third_party/CMakeFiles/OAuth2.dir/qt-oauth-lib/logindialog.cpp.o] Error 1
CMakeFiles/Makefile2:174: recipe for target 'third_party/CMakeFiles/OAuth2.dir/all' failed
make[1]: *** [third_party/CMakeFiles/OAuth2.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by NghiaTranUIT** [comment]
Ultimately, I was lucky to execute "make -j8" successfully [96%] and got the final error, which regard to `Linking CXX executable TogglDesktop`

```
[ 96%] Linking CXX executable TogglDesktop
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Qml.so.5.11.1: undefined reference to `QMetaEnumBuilder::setIsScoped(bool)@Qt_5_PRIVATE_API'
//home/parallels/Qt/5.11.1/gcc_64/lib/libQt5PrintSupport.so.5: undefined reference to `QPdfEngine::setPdfVersion(QPdfEngine::PdfVersion)@Qt_5_PRIVATE_API'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Qml.so.5.11.1: undefined reference to `QString::arg(QLatin1String, int, QChar) const@Qt_5'
//home/parallels/Qt/5.11.1/gcc_64/lib/libQt5PrintSupport.so.5: undefined reference to `QTime::toString(QStringView) const@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Quick.so.5.11.1: undefined reference to `QWindowPrivate::setVisible(bool)@Qt_5_PRIVATE_API'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5WebEngine.so.5.11.1: undefined reference to `qt_version_tag@Qt_5.11'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5WebEngineCore.so.5.11.1: undefined reference to `operator delete[](void*, unsigned long)@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Quick.so.5.11.1: undefined reference to `QWindowPrivate::shareContext() const@Qt_5_PRIVATE_API'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Quick.so.5.11.1: undefined reference to `qEnvironmentVariable(char const*)@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Quick.so.5.11.1: undefined reference to `QNativeGestureEvent::device() const@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Quick.so.5.11.1: undefined reference to `QRandomGenerator::_fillRange(void*, void*)@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Qml.so.5.11.1: undefined reference to `QtPrivate::compareStrings(QStringView, QStringView, Qt::CaseSensitivity)@Qt_5'
//home/parallels/Qt/5.11.1/gcc_64/lib/libQt5PrintSupport.so.5: undefined reference to `QFontMetrics::horizontalAdvance(QString const&, int) const@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Quick.so.5.11.1: undefined reference to `QNativeGestureEvent::~QNativeGestureEvent()@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Quick.so.5.11.1: undefined reference to `QNativeGestureEvent::QNativeGestureEvent(Qt::NativeGestureType, QTouchDevice const*, QPointF const&, QPointF const&, QPointF const&, double, unsigned long, unsigned long long)@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5WebEngine.so.5.11.1: undefined reference to `operator delete(void*, unsigned long)@Qt_5'
/home/parallels/Qt/5.11.1/gcc_64/lib/libQt5Quick.so.5.11.1: undefined reference to `QRandomGenerator64::global()@Qt_5'
collect2: error: ld returned 1 exit status
src/ui/linux/TogglDesktop/CMakeFiles/TogglDesktop.dir/build.make:707: recipe for target 'src/ui/linux/TogglDesktop/TogglDesktop' failed
make[2]: *** [src/ui/linux/TogglDesktop/TogglDesktop] Error 1
CMakeFiles/Makefile2:1267: recipe for target 'src/ui/linux/TogglDesktop/CMakeFiles/TogglDesktop.dir/all' failed
make[1]: *** [src/ui/linux/TogglDesktop/CMakeFiles/TogglDesktop.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

P/S: I've installed properly **sqlite3** and **openssl** since It was error at the first time I tried.

**Comment by MartinBriza** [comment]
Hm, seems there's something wrong when using binary Qt. Odd thing is I'm sure I managed to build with cmake on the `lin` buildbot...
Anyway, I'll look into this on Monday, today I'm working over a slow connection so downloading Ubuntu and Qt would take me all day.

**Comment by MartinBriza** [comment]
As per @IndrekV 's issue, it could be also caused by missing `qtbase5-private-dev` package

**Comment by NghiaTranUIT** [comment]
Unfortunately, after setting `LD_LIBRARY_PATH=/home/parallels/Qt/5.11.1/gcc_64/lib` and CMAKE_PREFIX_PATH  the error is still remaining 🤔 

Here is my ENV
<details>
  <summary>Env</summary>
  CLUTTER_IM_MODULE=xim
LD_LIBRARY_PATH=/home/parallels/Qt/5.11.1/gcc_64/lib
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_MENU_PREFIX=gnome-
LANG=en_US.UTF-8
DISPLAY=:1
QTDIR=/home/parallels/Qt/5.11.1/gcc_64/
OLDPWD=/home/parallels/Desktop/toggldesktop
GNOME_SHELL_SESSION_MODE=ubuntu
QMAKE=/home/parallels/Qt/5.11.1/gcc_64/bin/qmake
COLORTERM=truecolor
USERNAME=parallels
XDG_VTNR=2
SSH_AUTH_SOCK=/tmp/ssh-kTsTfJ4ijrO0/agent.3088
Qt5WebEngine_DIR=/home/parallels/Qt/5.11.1/gcc_64/lib/cmake/
XDG_SESSION_ID=4
USER=parallels
DESKTOP_SESSION=ubuntu
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/f1fbd29d_5df6_4a59_8469_14cb445c973a
PWD=/home/parallels/Desktop/toggldesktop/build
HOME=/home/parallels
TEXTDOMAIN=im-config
CMAKE_PREFIX_PATH=/home/parallels/Qt/5.11.1/gcc_64/lib/cmake/
SSH_AGENT_PID=3089
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_SESSION_DESKTOP=ubuntu
GJS_DEBUG_OUTPUT=stderr
GTK_MODULES=gail:atk-bridge
WINDOWPATH=2
TERM=xterm-256color
SHELL=/bin/bash
VTE_VERSION=5202
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
Qt5WebEngineWidgets_DIR=/home/parallels/Qt/5.11.1/gcc_64/lib/cmake/Qt5WebEngineWidgets
XDG_CURRENT_DESKTOP=ubuntu:GNOME
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GNOME_TERMINAL_SERVICE=:1.313
XDG_SEAT=seat0
SHLVL=1
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=parallels
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=/home/parallels/Qt/5.11.1/gcc_64//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/parallels-Parallels-Virtual-Platform:@/tmp/.ICE-unix/1714,unix/parallels-Parallels-Virtual-Platform:/tmp/.ICE-unix/1714
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
_=/usr/bin/env
</details>

What should we do now ☕️ ?

**Comment by MartinBriza** [comment]
Did you delete the build folder and run `cmake` again?

**Comment by NghiaTranUIT** [comment]
I managed to build and run Toggl successfully 💯 
screen shot 2019-01-02 at 16 11 55

The build time is diminished significantly than the original approach.

Good job @MartinBriza 🥇

**Comment by NghiaTranUIT** [comment]
```
/home/osboxes/toggldesktop/src/./database.h:9:31: fatal error: sqlite3.h: No such file or directory
compilation terminated.
```
Regarding Fatal Error on sqlite3, I encountered it, then solving by [the installation of sqlite](https://linuxhint.com/install-sqlite-ubuntu-linux-mint/)

**Comment by MartinBriza** [comment]
To set C++11 as the used C++ standard, you should rather use `set (CMAKE_CXX_STANDARD 11)`. Anyway, what is the system you're building on? Because in Ubuntu 18.04 the default standard is C++11.

And you're right, I actually hit the issue with SQLite when testing it in Ubuntu but forgot to commit a patch to fix this. Installing sqlite3 does 'fix' it but not really. Commit incoming in 3...2...1...

**Comment by IndrekV** [comment]
These 2 commits made things better. I'm on 16.04.1 LTS. Now I'm seeing missing openssl/crypto error.

```
In file included from /home/osboxes/toggldesktop/src/context.cc:33:0:
/home/osboxes/toggldesktop/third_party/poco/Crypto/include/Poco/Crypto/OpenSSLInitializer.h:24:28: fatal error: openssl/crypto.h: No such file or directory
compilation terminated.
src/CMakeFiles/TogglDesktopLibrary.dir/build.make:278: recipe for target 'src/CMakeFiles/TogglDesktopLibrary.dir/context.cc.o' failed
make[2]: *** [src/CMakeFiles/TogglDesktopLibrary.dir/context.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/osboxes/toggldesktop/third_party/poco/Crypto/include/Poco/Crypto/X509Certificate.h:22:0,
                 from /home/osboxes/toggldesktop/third_party/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from /home/osboxes/toggldesktop/third_party/poco/NetSSL_OpenSSL/include/Poco/Net/Utility.h:22,
                 from /home/osboxes/toggldesktop/third_party/poco/NetSSL_OpenSSL/include/Poco/Net/HTTPSClientSession.h:22,
                 from /home/osboxes/toggldesktop/src/netconf.cc:13:
/home/osboxes/toggldesktop/third_party/poco/Crypto/include/Poco/Crypto/OpenSSLInitializer.h:24:28: fatal error: openssl/crypto.h: No such file or directory
compilation terminated.
```
I'll try to add the correct include path to see if I can fix it with this.

**Comment by MartinBriza** [comment]
You have to have `libssl-dev` installed, I forgot to mention that in the changes.

**Pull request merged**
